### ISSUE TITLE
Add support for SSL Certificates

### ISSUE THREAD

**Issue by Subzidion** [LycheeOrg/Lychee-Docker#127]
The existing NGINX configuration serves everything on port 80. To support SSL, I had to make a few modifications to the NGINX configuration in the container. First, updated the existing server definition to listen to Port 443 and added the SSL relevant information:

```
 server {
        root /var/www/html/Lychee/public;
        listen       443 ssl;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_certificate /conf/fullchain.pem;
        ssl_certificate_key /conf/privkey.pem;
        ...
}
```

Then, I created a re-direct from Port 80 to the HTTPS endpoint:

```
server {
        listen 80;
        server_name <domain>;
        return 301 https://<domain>$request_uri;
    }
```

I generated the certificates on the host and placed them in the shared `/conf` volume so they'd be accessible from the container. I also mapped port 443 in the standard docker-compose.yml file.

Not sure if there's a way to make this "configurable" based on the presence of certificates, but figured I would explain how I got it to work here for others anyway.

**Comment by nicokaiser** [comment]
In my opinion, SSL termination should stay out of application containers and should be handled by a load balancer like [Traefik](https://traefik.io/) or [nginx-proxy](https://hub.docker.com/r/nginxproxy/nginx-proxy).

In cases where one needs to add SSL to the application container this should be kept a custom solution as this otherwise might lead to confusion.

**Comment by ildyria** [comment]
@nicokaiser sums-it up pretty nicely.
