### ISSUE TITLE
Error 507 NoWriteAccessOnLogsExceptions

### ISSUE THREAD

**Issue by louis6999** [LycheeOrg/Lychee-Docker#180]
Hi,

I use the docker-compose.yml provided in the code.
I don't have any problem to start my docker but when i try to connect i have this error 507
NoWriteAccessOnLogsExceptions
Could not write in the logs. Check that storage/logs/ and containing files have proper permissions.

**Comment by d7415** [comment]
> What GID/PID is necessary?

That only matters if you're accessing the files from outside the container, or on a system that limits such things.

> Skipping permissions setting (because those cmds give whack permissions inside the container) 

If you mean the ones in entrypoint, those set the *recommended* permissions inside the container.

> I am not using any .env

If you want Laravel to work, you're going to have to (or manually hack all of your settings into Lychee's files I suppose)

**Comment by d7415** [comment]
Ok, so.

1) You do not appear to be doing anything similar to the original issue, so this is the wrong place for this discussion
2) You appear to have an extremely unusual setup

> They break it (owner needed to stay 33 (www-data)). The built-in lychee is 1000 but www-data still couldn't read/write to it all.

The entrypoint script adds www-data (in the container) to the lychee group so that it has access.

> Also, `DB_SOCKET` is worthless. To anyone that finds it, you're welcome: `DB_HOST=localhost;unix_socket=/var/run/YOUR_SQL_SOCKET.sock`. Yes, the `unix_socket` in there is required or it just shits an error about files not being found, even if DB_SOCKET is used.

This is a very unusual setup. You are free to use the Docker image as you wish, but if you do unusual things it's on you to figure out how to make them work, which you are appear to have done.

**Comment by d7415** [comment]
> It doesn't

It does it at [build time](https://github.com/LycheeOrg/Lychee-Docker/blob/master/Dockerfile#L50) and again right [here](https://github.com/LycheeOrg/Lychee-Docker/blob/master/entrypoint.sh#L133).

This seems to work for every user who isn't you.

**Comment by d7415** [comment]
> I'm wondering if it is this NAS (a Qnap).

That's very possible. They sometimes do weird things to permissions.
