### ISSUE TITLE
Lychee On DigitalOcean Marketplace

### ISSUE THREAD

**Issue by mayailkour** [LycheeOrg/Lychee-Docker#37]
What do you think of putting [Lychee](https://lycheeorg.github.io/) on the [DigitalOcean Marketplace](https://marketplace.digitalocean.com/) to make the installation easier for noobs like me?

**Comment by d7415** [comment]
I don't see any issue in principle if any of the team are interested, but I think there would need to be a vested interest.
It doesn't seem overly complicated to set up, but:
* It's an extra deployment target, so potentially extra work at release time.
* Another configuration to support.
* The signup/initial setup looks fairly straightforward but would still take some time and requires approval from DO.
* There's no mention of any access to test environments - I certainly won't be paying them so that I can help debug issues!

**Comment by d7415** [comment]
Due to lack of expressed interest from the team and the issues listed above I'm closing this.
