### ISSUE TITLE
Should sqlite be the default?

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-Docker#49]
This would allow the gallery to run without a separate db container.

**Comment by roblandry** [comment]
I would say yes. However, to implement this, it should migrate to a db if provided, otherwise all uploads will be lost.

This was specifically done because I rather a separate db.

**Comment by d7415** [comment]
Yeah, I'm not sure about migration. I guess we could add a from/to flag that will migrate to or from a given external DB.

Yeah, the option to use external if desired should stay regardless.

**Comment by d7415** [comment]
The more I think about it, the more complicated migration seems. I think sqlite should be the default for new users because it saves setting up a DB server if you don't already have one running. That said, the way this is set up
- `.env` should be preserved on upgrades because it's in the /conf volume
-  The example specifies `DB_CONNECTION`, so anyone copying that will remain on mysql/mariadb

So this would only affect users who copy /uploads without /conf *and* don't specify `DB_CONNECTION`. Those users can run again with `DB_CONNECTION` set to get their photos "back".

**Comment by roblandry** [comment]
Yeah, but I'm not sure I personally like the idea of sticking someone into a particular db type. Thats the beauty of mariadb/mysql, it can be exported and imported elsewhere. Otherwise, a new user might decide first to use whats provided, upload 1000s of photos, only to have to reimport later when they want to move to mysql/Maria.

I'd say at a minimum, if defaults to sqlite with no migration path, a disclaimer should be on the Readme and possibly in the entrypoint.sh. Following that, the user has been warned.

**Comment by roblandry** [comment]
But I do like having it as an "easy" installation option.

**Comment by d7415** [comment]
I'd have to test it, but it should be a matter of dumping from sqlite and running the sql in mariadb/whatever. I'll try to find time this weekend, then I can document that :)

Providing our own solution sounds like a pain, but instructions should be ok.

**Comment by d7415** [comment]
Thanks for keeping me in check :)

**Comment by d7415** [comment]
It's not pretty, but [I did it](https://github.com/LycheeOrg/Lychee-Laravel-Docker/wiki/(Slightly%3F)-messy-migration-between-DB-engines).
