### ISSUE TITLE
Docker nginx upload limited to 100MB

### ISSUE THREAD

**Issue by Erriez** [LycheeOrg/Lychee-Docker#63]
Increasing the upload limits in `.user.ini` as described [i-cant-upload-photos](https://lycheeorg.github.io/docs/faq.html#i-cant-upload-photos) is not sufficient when using docker-compose, because the upload limit must be increased in the `nginx.conf` file as well. I found the following workaround:
```
docker exec -it lychee bash
apt update; apt install nano

nano /etc/nginx/nginx.conf
    client_max_body_size 1000M;
    
nano /var/www/html/Lychee/public/.user.ini
    max_execution_time = 200
    post_max_size = 200M
    upload_max_size = 1000M
    upload_max_filesize = 1000M
    max_file_uploads = 2000

Restart docker or docker-compose
```

**Comment by d7415** [comment]
This is documented in the [README](https://github.com/LycheeOrg/Lychee-Docker#advanced-configuration).

**Comment by Erriez** [comment]
I followed the documentation in [README](https://github.com/LycheeOrg/Lychee-Docker#advanced-configuration), but it does not work:

> Note that nginx will accept by default images up to 100MB (client_max_body_size 100M) and that PHP parameters are overridden according to the recommendations of the Lychee FAQ.

Overriding PHP parameters as described on [recommendations of the Lychee FAQ](https://lycheeorg.github.io/docs/faq.html#i-cant-upload-photos) is not sufficient in `/var/www/html/Lychee/public/.user.ini`. 
The nginx configuration file `/etc/nginx/nginx.conf` setting `client_max_body_size` must be increased as well, otherwise files bigger than 100MB cannot be uploaded.

 [recommendations of the Lychee FAQ](https://lycheeorg.github.io/docs/faq.html#i-cant-upload-photos) does not mention anything about this nginx configuration.

**Comment by d7415** [comment]
The part of the README I linked to, "Advanced configuration", explicitly mentions the nginx configuration.

**Comment by nanawel** [comment]
Putting in my 2 cents here, I came to the same conclusion as @Erriez.
The documentation clearly instructs 

> If you need to add (not change) nginx directives, files mounted in /etc/nginx/conf.d/ will be included in the http context.

but it won't be applied to the virtual host, at least not any overriden value of `client_max_body_size`.

You _have_ to override the entire `nginx.conf` file and change the value there. Creating a new `*.conf` file that you would mount in `/etc/nginx/conf.d/` won't help, although `nginx -T` output's ends with

```
...
# configuration file /etc/nginx/conf.d/client_max_body_size.conf:
client_max_body_size 1G;
```

In my understanding, it simply due to the fact that you're including the file in the `http` block while the default file defines the value at the `server` level (higher priority).

**Comment by nanawel** [comment]
This use case seems to be so common, that would be nice to have an easier way to implement it.
But anyway, it works in the end, that's fine.

Thanks @d7415 :+1:
